name: Deploiement
# les jobs vont se déclencher à chaque push sur la
# branche main
on:
    push:
        branches: main

jobs:
    # le nom du job (build, test, deploy)
    deploy:
        # définir le runner qui éxécutera les étapes
        runs-on: ubuntu-latest
        # les étapes du job
        steps:
            # prendre de code sur git et le placer sur ubuntu
            - name: Checkout
              uses: actions/checkout@v4
            - name: Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ftp.samkirkland.com
                  username: myFtpUserName
                  password: ${{ secrets.ftp_password }}
