name: Deploiement
# les jobs vont se déclencher à chaque push sur la
# branche main
on:
    push:
        branches: main

jobs:
    # le nom du job (build, test, deploy)
    deploy:
        # définir le runner qui éxécutera les étapes
        runs-on: ubuntu-latest
        # les étapes du job
        steps:
            - name: step 1
              run: echo '42'
